universe = vanilla

log    = log/yearm_$(Cluster)_$(Process).log
error  = error/yearm_$(Cluster)_$(Process).err
output = output/yearm_$(Cluster)_$(Process).out

executable = ./yearmean.sh
arguments = $(filename)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, packages.tar.gz, yearmean.R, $(filename)

request_cpus = 1
request_memory = 4GB
request_disk =4GB

queue filename from yearname.txt