universe = vanilla

log    = log/year_$(Cluster)_$(Process).log
error  = error/year_$(Cluster)_$(Process).err
output = output/year_$(Cluster)_$(Process).out

executable = ./year.sh
arguments = $(filename) 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, packages.tar.gz, year.R, $(filename)

request_cpus = 1
request_memory = 4GB
request_disk =4GB

queue filename from splitnames.txt